export const CHANGE_ACTIVE_NOTE = 'NOTES/CHANGE_ACTIVE_NOTE'
export const NOTES_LOADED = 'NOTES/NOTES_LOADED'

export const START_LOADING = 'APP/START_LOADING'
export const FINISH_LOADING = 'APP/FINISH_LOADING'
